accounts/urls.py
from django.urls import URLPattern, path
from . import views

app_name = 'accounts'
urlpatterns = [
	path('register/', views.UserRegister.as_view()),
 
 
 ]

shop/urls.py
from django.urls import path, include
from . import views


app_name = 'shop'
urlpatterns = [
	path('', views.Home.as_view(), name='home'),
]

y/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    
]

accounts/models.py
from .managers import UserManager
from django.db import models
from django.contrib.auth.models import AbstractUser , PermissionsMixin


class CustomUser(AbstractUser):
    phone_number = models.CharField(max_length=11, unique=True)
    full_name = models.CharField(max_length=100)
    job = models.CharField(max_length=100, blank=True, null=True)
    is_legal = models.BooleanField(default=False)

    # objects = UserManager()
    UserManagers = UserManager()
    # objects = UserManager



    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ('email' ,'full_name')
    
class Kid(models.Model):
    pass
    # list_relative = (("pedar", "پدر"),("daii", "دایی"),("amo", "عمو"),)
    # relative = models.CharField(choise=list_relative, max_length=20)
    # relative_user = models.ForeignKey(User, on_delete=models.CASCADE)
    # qad = models.IntegerField()
    # vazn = models.IntegerField()
    #  age = models.IntegerField()
    # sex =models.BooleanField()
    # numx = models.IntegerField()

shop/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from dataclasses import field
from pyexpat import model
from django import forms
from .models import CustomUser
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class UserCreationForm(forms.ModelForm):
    """
    A form for user registerion 
    """
    password1 = forms.CharField(label='password' , widget= forms.PasswordInput)
    password2 = forms.CharField(label='confirm password' , widget= forms.PasswordInput)
    
    class Meta:
        model = CustomUser
        fields = ('email' ,'full_name' , 'phone_number')
        
    def clean_password2(self):
        """
        password check
        """
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise ValidationError ('password is not match')
        return cd['password2']
    
    def save(self, commit=True):
        user =  super().save(commit=False)
        user.set_password(self.changed_data['password1'])
        if commit:
            user.save()
        return user
    
    
class UserChangeForm(forms.ModelForm):
    """
    cheange user info 
    """
    password = ReadOnlyPasswordHashField(help_text="you can change password using <a href=\"../password/\">this form</a>.")
    
    class Meta:
        model = CustomUser
        fields = ('email' ,'full_name' , 'phone_number' , 'last_login')
    

accounts/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import UserRegisterSerializer, UserSerializer
from rest_framework import status
from rest_framework import viewsets
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import UserRegisterSerializer, UserSerializer
from rest_framework import status
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404

class UserRegister(APIView):
	def post(self, request):
		ser_data = UserRegisterSerializer(data=request.POST)
		if ser_data.is_valid():
			ser_data.create(ser_data.validated_data)
			return Response(ser_data.data, status=status.HTTP_201_CREATED)
		return Response(ser_data.errors, status=status.HTTP_400_BAD_REQUEST)


	def get(self , request):
	 	return Response({'name':'koskesh'})

shop/views.py
from rest_framework.views import APIView
from rest_framework.response import Response

class Home(APIView):
    def get(self , request):
       return Response({'name':'jak'})
   
   

classmethod
class classname(object):
    """
    docstring
    """
    pass

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send">
    </form>
{% endblock %}

accounts/templates/accounts/verify.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send">
    </form>
{% endblock %}

shop/templates/shop/home.html
{% extends "base.html" %}

{% block content %}

    <p class="form-text text-muted">
        Help Text
    </p>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Online Shop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base_styles.css' %}">
    {% block extra_headers %} {% endblock %}
</head>
<body>

    {% include 'inc/navbar.html' %}
    <div class="jumbotron">
        {% include 'inc/messages.html' %}
        {% block content %} {% endblock %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'shop:home' %}">Home</a>
            {% comment %} {% if request.user.is_authenticated %}
            <a class="nav-link active" href="{% url 'accounts:user_logout' %}">Logout</a>
            {% else %}
            <a class="nav-link active" href="{% url 'accounts:user_register' %}">Register</a>
            <a class="nav-link active" href="{% url 'accounts:user_login' %}">Login</a>
            {% endif %}
            {% if request.user.is_admin %}
            <a class="nav-link active" href="{% url 'home:bucket' %}">Bucket</a>
            {% endif %}
            <a class="nav-link active" href="{% url 'orders:cart' %}">CART {{ cart|length }}</a> {% endcomment %}
        </div>
    </div>
</nav>